name: Compila e substitui os Componentes

on:
  workflow_dispatch:

jobs:
  compare-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Baixa o Arduino-lib-builder
      run: | 
        git clone https://github.com/bmorcelli/esp32-arduino-lib-builder.git
        cd esp32-arduino-lib-builder
        git branch -r
        git checkout -b release/v4.4 origin/release/v4.4
        git pull origin release/v4.4
        rm -rf ./tools/sdk/*
        
        
    - name: Instala os pr√©-requisitos
      run: bash ./esp32-arduino-lib-builder/tools/prepare-ci.sh
      
    - name: Build Libs for esp32
      run: |
        cd esp32-arduino-lib-builder
        bash ./build.sh -I 'release/v4.4' -A 'idf-release/v4.4' -c '/home/runner/work/arduino-esp32/arduino-esp32/'

    - name: Set up Git
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        
    - name: Compare JSON files
      id: compare
      run: |
        git add .
        git commit -m "Components Update"
        git push
